config/routes.rb
Rails.application.routes.draw do
  resources :account_verification_documents
  resources :account_verification

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ActiveRecord::Base
  
end

app/models/account_verification_document.rb
class AccountVerificationDocument < ActiveRecord::Base 
  include ImageUploader::Attachment(:file)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/services/account_verification_document/load_files.rb
module Services
  module AccountVerificationDocument
    class LoadFiles
      def initialize(params)
        @params = params[:account_verification_document]
        @account_verification_document = get_file(@params)
        @account = params[:account]
      end

      def create
        account_verification_document = ::AccountVerificationDocument.create(get_file(@params))
        account_verification_document.update(account_id: @account.id, file_id: @params[:file_id].to_i)
        
      end

      private

      def validate
      
      end

      def get_file(params)
        params.require(:account_verification_document).permit(:file)
      end
    end
  end
end

app/controllers/account_verification_controller.rb
class AccountVerificationController < ApplicationController
  #before_action :set_account_verification_document, only: %i[ show edit update destroy ]

  # GET /account_verification_documents or /account_verification_documents.json
  def index
    @account_verification_documents = AccountVerificationDocument.all
  end

  # GET /account_verification_documents/1 or /account_verification_documents/1.json
  def show
  end

  # GET /account_verification_documents/new
  def new
   @account_verification_document = AccountVerificationDocument.new
  end

  # GET /account_verification_documents/1/edit
  def edit
  end


  def create
#    @account_verification_document = AccountVerificationDocument.new(account_verification_document_params)

    #respond_to do |format|
      #if @account_verification_document.save
        #format.html { redirect_to account_verification_document_url(@account_verification_document), notice: "Account verification document was successfully created." }
        #format.json { render :show, status: :created, location: @account_verification_document }
      #else
        #format.html { render :new, status: :unprocessable_entity }
        #format.json { render json: @account_verification_document.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /account_verification_documents/1 or /account_verification_documents/1.json
  def update
    # binding.pry
    
    respond_to do |format|
      if Account.find(params[:id].to_i).update(verification_status: 1)
        format.html { redirect_to account_verification_index_url(@account_verification_document), notice: "Your status is pending." }
        format.json { render :show, status: :ok, location: @account_verification_document }

      end
    end
 #   respond_to do |format|
      #if @account_verification_document.update(account_verification_document_params)
        #format.html { redirect_to account_verification_document_url(@account_verification_document), notice: "Account verification document was successfully updated." }
        #format.json { render :show, status: :ok, location: @account_verification_document }
      #else
        #format.html { render :edit, status: :unprocessable_entity }
        #format.json { render json: @account_verification_document.errors, status: :unprocessable_entity }
      #end
 #   end
  end

  # DELETE /account_verification_documents/1 or /account_verification_documents/1.json
  def destroy
  #  @account_verification_document.destroy

    #respond_to do |format|
      #format.html { redirect_to account_verification_documents_url, notice: "Account verification document was successfully destroyed." }
      #format.json { head :no_content }
  #  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_verification_document
      @account_verification_document = AccountVerificationDocument.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_verification_document_params
      params.require(:account_verification_document).permit(:title, :image)
    end
end

app/controllers/account_verification_documents_controller.rb
require 'pry'
class AccountVerificationDocumentsController < ApplicationController
  before_action :set_account_verification_document, only: %i[ show edit update destroy ]

  # GET /account_verification_documents or /account_verification_documents.json
  def index
    @account_verification_documents = AccountVerificationDocument.all
  end

  # GET /account_verification_documents/1 or /account_verification_documents/1.json
  def show
  end

  # GET /account_verification_documents/new
  def new
    @account_verification_document = AccountVerificationDocument.new
  end

  # GET /account_verification_documents/1/edit
  def edit
  end

  # POST /account_verification_documents or /account_verification_documents.json
  def create
    @account_verification_document = AccountVerificationDocument.find_by(account_id: Account.last.id, file_id: params[:file_id].to_i)
    if @account_verification_document
      binding.pry
      update
    else
      respond_to do |format|
        Services::AccountVerificationDocument::LoadFiles.new(account_verification_document: params, account: Account.last).create
        #if @account_verification_document.save
        #format.html { redirect_to account_verification_document_url(@account_verification_document), notice: "Account verification document was successfully created." }
        #format.json { render :show, status: :created, location: @account_verification_document }
        #else
        #format.json { render json: @account_verification_document.errors, status: :unprocessable_entity }
        format.html { redirect_to new_account_verification_url, notice: "Account verification document was successfully created." }
        #end
      end
    end
  end

  # PATCH/PUT /account_verification_documents/1 or /account_verification_documents/1.json
  def update
    respond_to do |format|
      binding.pry
      @account_verification_document.update(account_verification_document_params)
      format.html { redirect_to new_account_verification_url, notice: "Account verification document was successfully created." }
    end
  end

  # DELETE /account_verification_documents/1 or /account_verification_documents/1.json
  def destroy
    @account_verification_document.destroy

    respond_to do |format|
      format.html { redirect_to account_verification_documents_url, notice: "Account verification document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_account_verification_document
    @account_verification_document = AccountVerificationDocument.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def account_verification_document_params    
    params.require(:account_verification_document).permit(:file)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/account_verification/_form.html.erb
<%= form_with(model: account_verification_document) do |form| %>
  <% if account_verification_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_verification_document.errors.count, "error") %> prohibited this account_verification_document from being saved:</h2>

      <ul>
        <% account_verification_document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Ine" %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
    <%= hidden_field_tag(:file_id, "1") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

<%= form_with(model: account_verification_document) do |form| %>
  <% if account_verification_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_verification_document.errors.count, "error") %> prohibited this account_verification_document from being saved:</h2>

      <ul>
        <% account_verification_document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Comprobante domicilio" %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
    <%= hidden_field_tag(:file_id, "2") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>

<%= form_with(model: account_verification_document) do |form| %>
  <% if account_verification_document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_verification_document.errors.count, "error") %> prohibited this account_verification_document from being saved:</h2>

      <ul>
        <% account_verification_document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "RFC" %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
    <%= hidden_field_tag(:file_id, "3") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/account_verification/edit.html.erb
<h1>Editing Account Verification Document</h1>

<%= render 'form', account_verification_document: @account_verification_document %>

<%= link_to 'Show', @account_verification_document %> |
<%= link_to 'Back', account_verification_documents_path %>

app/views/account_verification/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Verification Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_verification_documents.each do |account_verification_document| %>
      <tr>
        <td><%= account_verification_document.file_data %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Verification Document', new_account_verification_path %>

app/views/account_verification/new.html.erb
<h1>New Account Verification Document</h1>

<%= render 'form', account_verification_document: @account_verification_document %>

<%= link_to 'Back', account_verification_index_path %>

<%= link_to 'Crear lote de guías', account_verification_path(id: Account.last.id), 
class: 'btn btn-primary-manuable rounded-pill fs-5', role: 'button', method: :put %>

app/views/account_verification/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>

<p>
  <strong>Image data:</strong>
</p>

app/views/layouts/account_verification_documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Verification Documents</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_verification_documents.each do |account_verification_document| %>
      <tr>
        <td><%= account_verification_document.title %></td>
        <td><%= account_verification_document.image_data %></td>
        <td><%= link_to 'Show', account_verification_document %></td>
        <td><%= link_to 'Edit', edit_account_verification_document_path(account_verification_document) %></td>
        <td><%= link_to 'Destroy', account_verification_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Verification Document', new_account_verification_document_path %>

app/views/layouts/account_verification_documents/new.html.erb
<h1>New Account Verification Document</h1>

<%= render 'form', account_verification_document: @account_verification_document %>

<%= link_to 'Back', account_verification_documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestManuableRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>